### ISSUE TITLE
No measures...

### ISSUE THREAD

**Issue by tk5ep** [EdwinCroissantArduinoLibraries/SimpleHX712#1]
Hi,
I have build a pcb with an Arduino pro mini and four HX712.
I try to use your library, and another one made for the HX711, but none of these give me something usable.
With a weight cell connected, i can get an initial value, but unstable.
But no variation at all when putting some weight on the cell.
I can get some datas when unbalacing the differential inputs with a resistor. But that would correspond to a very high weight. It is like if the HX712 has a very low amplification factor. Communication seems to be OK, i can change the gain and power-on or off.
Previous tests with HX711 gave good results.
Did you get something out of these chips or are they just crap and fake ?

**Comment by tk5ep** [comment]
I answer myself...
It was a hardware problem, AVDD being different then REFP on cell.

BTW, i can't switch to gain 256 as you mentionend, even with another libray i modified. I have the same batch of ICs as you.. Are they fake ?

**Comment by EdwinCroissant** [comment]
I don’t think these chips are fake, but who knows, everything is possible. :). Thank you for letting me know it was a hardware problem.
